FROM supplantr/python-toolbox

RUN dnf install -y python-pillow
RUN dnf install -y python-gobject
RUN dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
RUN dnf install -y ffmpeg
